# Generated by Django 3.1.5 on 2023-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('meter_address', models.CharField(max_length=255)),
                ('status', models.CharField(default='Live', max_length=10, verbose_name=[('Live', 'Live'), ('Down', 'Down')])),
                ('data_point', models.DateTimeField()),
                ('average_current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('active_power_W', models.FloatField()),
                ('apparent_power_VA', models.FloatField()),
                ('active_energy_Wh', models.FloatField()),
                ('apparent_energy_VAh', models.FloatField()),
                ('phase_current', models.FloatField()),
                ('neutral_current', models.FloatField()),
                ('frequency', models.FloatField()),
                ('meter_time', models.DateTimeField()),
                ('pf', models.FloatField()),
                ('bg_color', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
